// <auto-generated />
namespace Exposure.Web.DataContexts.IdentityMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class RegDateFix : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RegDateFix));
        
        string IMigrationMetadata.Id
        {
            get { return "201809091425316_RegDateFix"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
